# Generated by Django 3.2.9 on 2022-01-08 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='transaction_list',
            new_name='transactions',
        ),
    ]
