# Generated by Django 3.2.11 on 2022-07-02 00:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_rename_transaction_list_group_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code_id',
            field=models.CharField(default=uuid.uuid4, max_length=6, unique=True),
        ),
    ]
